name: retorno_sucesso_ou_erro_package
description: Package para retornar o resultado da função determinando o sucesso ou erro.
version: 2.0.0
homepage: https://github.com/pwlimaverde/retorno_sucesso_ou_erro_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.0.1-dev.10
  flutter_test:
    sdk: flutter

flutter: